# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
baseUrl = "https://barjacobi.com/"
defaultContentLanguage = "en"
paginate = 10
theme = 'congo'
enableRobotsTXT = true
summaryLength = 0
canonifyURLs = true
relativeURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true