title = "Bar Jacobi's Blog"

[params.author]
  name = "Bar Jacobi"
  image = "img/avatar.jpg"
  headline = "A generally awesome human"
  bio = "A little bit about me"
  links = [
    { github = "https://github.com/barjacobi" },
  ]
