languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Bar Jacobi"

[params.author]
  name = "Bar Jacobi"
  image = "img/avatar.jpg"
  headline = "MSc Student @ Tel Aviv University | Bioinformatics"
  # bio = "A little bit about me"
  links = [
    { linkedin = "https://www.linkedin.com/in/bar-jacobi" },
    { github = "https://github.com/barjacobi" },
    { email = "mailto:baraveh@gmail.com" },
    { orcid = "https://orcid.org/0009-0002-0638-399X"},
    { google-scholar = "https://scholar.google.com/citations?user=Pjly-lwAAAAJ"},
  ]
